openapi: 3.0.0
info:
  title: Sample API
  description: Test project for monstar-lab
  version: 0.1.0
#servers:
#  - url: http://api.example.com/v1
#    description: Optional server description, e.g. Main (production) server
#  - url: http://staging-api.example.com
#    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: Users 
    description: /users/* endpoints
  - name: Authentication 
    description: authentication-related endpoints
  - name: Favorites
    description: /favorites/* endpoints
paths:
  /auth:
    post:
      tags:
        - Authentication
      summary: Authenticates the user.
      description: User has to be already created
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '201':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authentication'
  /users:
    get:
      tags:
        - Users
      summary: Returns a list of users.
      description: Requires admin permission.
      security: 
        - bearerAuth: []
      responses:
        '200':   
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/User'
  /favorites:
    get:
      tags:
        - Favorites
      summary: Returns favorites of the current user
      description: Requires a valid JWT token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'
# Components
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        _id: 
          type: string
          #description: User _id
        email:
          type: string
          #description: users email
        permissionFlags:
          type: number
          #description: users permission level
        __v:
          type: number
          #description: mongoDB object version key
    Login:
      title: Login
      type: object
      properties:
        email:
          type: string
          #description: users email
        password:
          type: string
          #description: users password
    Authentication: 
      title: Authentication Tokens
      type: object
      properties:
        accessToken:
          type: string
          #description: accessToken 
        refreshToken: 
          type: string
          #description: refreshToken 
    Video:
      title: Video
      type: object
      properties:
        name:
          type: string
        description:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 