openapi: 3.0.0
info:
  title: Sample API
  description: Test project for monstar-lab
  version: 0.1.0
#servers:
#  - url: http://api.example.com/v1
#    description: Optional server description, e.g. Main (production) server
#  - url: http://staging-api.example.com
#    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: Authentication 
    description: authentication-related endpoints
  - name: Users 
    description: /users/* endpoints
  - name: Movies
    description: /movies/* endpoints
  - name: Favorites
    description: /favorites/* endpoints
paths:
  /auth:
    post:
      tags:
        - Authentication
      summary: Authenticate the user
      description: User has to be already created
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '201':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authentication'
  /users:
    get:
      tags:
        - Users
      summary: Return a list of users
      description: Requires admin permission
      security: 
        - bearerAuth: []
      responses:
        '200':   
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/User'
  /movies:
    get:
      tags:
        - Movies
      summary: Return a list of movies
      description: Supports 'search' query parameter
      parameters:
        - in: query
          name: search
          schema: 
            type: string
          description: string to search inside names or descriptions of movies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
  
  /favorites:
    get:
      tags:
        - Favorites
      summary: Return favorites of the current user
      description: Requires a valid JWT token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
        '401':
          description: Unauthorized   
  /favorites/{movieId}:
    post:
      tags:
        - Favorites
      summary: Favorite a selected movie for the current user
      description: Requires a valid JWT token
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: movieId
          schema: 
            type: string
          required: true
          description: String ID of the movie to favorite
      responses:
        '204':
          description: Successfully added to favorites
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorsResponse'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorsResponse'
    delete:
      tags:
        - Favorites
      summary: Delete a selected movie from the favorites of the current user
      description: Requires a valid JWT token
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: movieId
          schema: 
            type: string
          required: true
          description: String ID of the movie to delete from favorites
      responses:
        '204':
          description: Successfully deleted from favorites
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorsResponse'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorsResponse'
          

# Components
components:
  schemas:
    ErrorsResponse:
      title: ErrorResponse
      type: object
      properties:
        errors: 
          type: array
          items: 
            type: string
            description: Error message
    User:
      title: User
      type: object
      properties:
        _id: 
          type: string
          #description: User _id
        email:
          type: string
          #description: users email
        permissionFlags:
          type: number
          #description: users permission level
        __v:
          type: number
          #description: mongoDB object version key
    Login:
      title: Login
      type: object
      properties:
        email:
          type: string
          #description: users email
        password:
          type: string
          #description: users password
    Authentication: 
      title: Authentication Tokens
      type: object
      properties:
        accessToken:
          type: string
          #description: accessToken 
        refreshToken: 
          type: string
          #description: refreshToken 
    Movie:
      title: Movie
      type: object
      properties:
        name:
          type: string
        description:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 